using System.Globalization;

namespace NEM.CLI.Tests;

internal sealed class EpwFixture
{
    private readonly List<string> _rows = [];

    public string City { get; init; } = "Test City";
    public string Wmo { get; init; } = "012345";
    public double Latitude { get; init; } = -33.86;
    public double Longitude { get; init; } = 151.21;
    public double TimeZone { get; init; } = 10;
    public bool LeapYearObserved { get; init; }
    public int NumberOfDataPeriods { get; init; } = 1;
    public int RecordsPerHour { get; init; } = 1;
    public bool BlankLineBeforeDataPeriods { get; init; }
    public string DataPeriodsTrailingText { get; init; } = string.Empty;

    public EpwFixture AddRow(
        int year,
        int month,
        int day,
        int hour,
        double globalHorizontalRadiation = 0,
        double directNormalRadiation = 0,
        double windSpeed = 5,
        double diffuseHorizontalRadiation = 0,
        string flags = "?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9*9?9*9*9?9*9")
    {
        var columns = Enumerable.Repeat("0", 22).ToArray();
        columns[0] = year.ToString(CultureInfo.InvariantCulture);
        columns[1] = month.ToString(CultureInfo.InvariantCulture);
        columns[2] = day.ToString(CultureInfo.InvariantCulture);
        columns[3] = hour.ToString(CultureInfo.InvariantCulture);
        columns[5] = flags;
        columns[13] = globalHorizontalRadiation.ToString(CultureInfo.InvariantCulture);
        columns[14] = directNormalRadiation.ToString(CultureInfo.InvariantCulture);
        columns[15] = diffuseHorizontalRadiation.ToString(CultureInfo.InvariantCulture);
        columns[21] = windSpeed.ToString(CultureInfo.InvariantCulture);
        _rows.Add(string.Join(',', columns));
        return this;
    }

    public string Write()
    {
        string path = Path.Combine(Path.GetTempPath(), $"nemsim-{Guid.NewGuid():N}.epw");
        var lines = new List<string>
        {
            FormattableString.Invariant($"LOCATION,{City},NSW,AUS,Synthetic,{Wmo},{Latitude},{Longitude},{TimeZone},40"),
            "DESIGN CONDITIONS,0",
            "TYPICAL/EXTREME PERIODS,0",
            "GROUND TEMPERATURES,0",
            $"HOLIDAYS/DAYLIGHT SAVINGS,{(LeapYearObserved ? "Yes" : "No")},0,0,0",
            "COMMENTS 1,Synthetic test fixture",
            "COMMENTS 2,Generated by NEM.CLI.Tests",
        };

        if (BlankLineBeforeDataPeriods)
        {
            lines.Add(string.Empty);
        }

        lines.Add($"DATA PERIODS,{NumberOfDataPeriods},{RecordsPerHour},Data,Sunday,1/1,12/31{DataPeriodsTrailingText}");
        lines.AddRange(_rows);
        File.WriteAllLines(path, lines);
        return path;
    }
}
